name: ${BASENAME}

services:
  ingress:
    image: ${INGRESS_IMAGE}
    restart: always
    container_name: ${BASENAME}-ingress
    hostname: ${BASENAME}-ingress
    ports:
      - 443:8443
      - 80:8080
    env_file: ./app.env
    environment:
      # using .env variables to define or override app.env
      - BACKEND=${BASENAME}-app:9000
      - SERVERNAME=${SERVERNAME}
      - LOAD_MODULES=${LOAD_MODULES}
    volumes:
      - ./src/html:/var/www/html:ro
      - ./src/public:/var/www/public:ro
      - ./docker/nginx/certs:/etc/nginx/certs:ro
      - ./docker/nginx/templates/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
      - ./docker/nginx/templates/conf.d/empty.conf.template:/etc/nginx/templates/conf.d/logging.conf.template:ro
      - ./docker/nginx/templates/conf.d/empty.conf.template:/etc/nginx/templates/includes/proxy_backend.conf.template:ro
      - ./docker/nginx/templates/conf.d/empty.conf.template:/etc/nginx/templates/includes/proxy_backend_ssl.conf.template:ro
      - ./docker/nginx/templates/conf.d/00-http-common.conf.template:/etc/nginx/templates/conf.d/00-http-common.conf.template:ro
      - ./docker/nginx/templates/conf.d/default.conf.template:/etc/nginx/templates/conf.d/default.conf.template:ro
      - ./docker/nginx/templates/conf.d/app.conf.template:/etc/nginx/templates/conf.d/app.conf.template:ro
      - ./docker/nginx/templates/includes/server-common.conf.template:/etc/nginx/templates/includes/server-common.conf.template:ro
      - ./src/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:/opt/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:ro
      - ./src/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf:/opt/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf:ro
    depends_on:
      - app
    security_opt:
      - no-new-privileges:true
    networks:
      - isolated
      - public

  app:
    restart: always
    container_name: ${BASENAME}-app
    hostname: ${BASENAME}-app
    env_file: ./app.env
    build:
      context: ./docker/php
    volumes:
      - ./src/public:/var/www/public
    environment:
      - PHP_ERROR_REPORTING=E_ALL
    user: "www-data:www-data"
    security_opt:
      - no-new-privileges:true
    networks:
      - isolated

networks:
  isolated:
    driver: bridge
    internal: true
  public:
    driver: bridge